#!/bin/sh

# Simple shellscript for creating a standard C file

if [ "$#" -ne 1 ];
then
	echo "Usage: cfile [name]" >&2
	exit 2
fi

echo "// Library inclusion
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Defining pseudo-variables
#define TRUE 1
#define FALSE 0
#define INT_MAX 2147483647
#define INT_MIN -2147483648

// Function prototypes


// Creating data types and structs


int main(int argc, char *argv[])
{


	return 0;
}

// Functions" > $1

echo "'$1' created successfully"
